### ISSUE TITLE
Weapons in a no-weapons server

### ISSUE THREAD

**Issue by PathosEthosLogos** [Redix/teeworlds#5]
http://race.teesites.net/maps/13/

I just made a record in ctf2-no-weapons because I used weapons under no-weapons settings.

https://github.com/PathosEthosLogos/tw/blob/master/Teerace%20FastCap%20no-weapons

This was the config I was using for the no-weapons server, but for some reason, weapons showed up anyway. Initially, there were no weapons. I'm not sure what happened here.

**Comment by Redix** [comment]
This issue was with a old version of the server. Should be fixed in the latest code.
